on:
  pull_request:
  push:
    branches: [main]

jobs:
  build:
    name: Build Flake check
    runs-on: macos-13
    steps:
      - uses: actions/checkout@v3
      - uses: DeterminateSystems/nix-installer-action@main
      - run: nix build -vvv --log-format raw .
